# build container
FROM node:alpine

RUN apk --no-cache add \
    g++ \
    make \
    python3

WORKDIR /usr/src/maw-files
COPY "package*.json" .

ENV NG_CLI_ANALYTICS=off
RUN npm install

COPY . .

RUN npm run dev_build


# dev container
FROM nginx:alpine

WORKDIR /srv/www/maw-files

RUN rm /etc/nginx/conf.d/*

COPY etc/nginx/tls.conf                   /etc/nginx
COPY etc/nginx/nginx.conf                 /etc/nginx
COPY etc/nginx/h5bp                       /etc/nginx/h5bp
COPY etc/nginx/conf.d/dev.maw-files.conf  /etc/nginx/conf.d/maw-files.conf
COPY --from=0                             /usr/src/maw-files/dist .

CMD [ "nginx", "-g", "daemon off;" ]
EXPOSE 10443
